'use strict';
console.log('Truth table for conjunction');
console.log('var1\tvar2\tvar1 && var2');
let var1 = true;
let var2 = true;
let outcome = true;
console.log(var1 + '\t' + var2 + '\t' + outcome);
var1 = true;
var2 = false;
outcome = false;
console.log(var1 + '\t' + var2 + '\t' + outcome);
var1 = false;
var2 = true;
outcome = false;
console.log(var1 + '\t' + var2 + '\t' + outcome);
var1 = false;
var2 = false;
outcome = false;
console.log(var1 + '\t' + var2 + '\t' + outcome);