console.log('Truth table for disjunction of 3 conditions')
console.log('var1\tvar2\tvar3\tvar1 || var2 || var3');
let var8 = true;
let var9 = true;
let var10 = true;
let outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = true;
var9 = true;
var10 = false;
outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = true;
var9 = false;
var10 = true;
outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = true;
var9 = false;
var10 = false;
outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = false;
var9 = true;
var10 = true;
outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = false;
var9 = true;
var10 = false;
outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = false;
var9 = false;
var10 = true;
outcome4 = true;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);
var8 = false;
var9 = false;
var10 = false;
outcome4 = false;
console.log(var8 + '\t' + var9 + '\t' + var10 + '\t' + outcome4);