console.log('Truth table for conjunction of 3 conditions')
console.log('var1\tvar2\tvar3\tvar1 && var2 && var3')
let var5 = true;
let var6 = true;
let var7 = true;
let outcome3 = true;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = true;
var6 = true;
var7 = false;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = true;
var6 = false;
var7 = true;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = true;
var6 = false;
var7 = false;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = false;
var6 = true;
var7 = true;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = false;
var6 = true;
var7 = false;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = false;
var6 = false;
var7 = true;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);
var5 = false;
var6 = false;
var7 = false;
outcome3 = false;
console.log(var5 + '\t' + var6 + '\t' + var7 + '\t' + outcome3);